name: 'Log Finder'

description: 'Search a string to find all contained log files'

inputs:
  content:
    description: 'The string to search for log files in'
    required: false
  content-path: 
    description: 'The file which contains the string to search for log files in'
    required: false
  file-suffix:
    description: 'File suffix'
    required: true
    default: 'log'

outputs:
  log-files:
    description: 'The log files that were found'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: file-text
  color: green
